# Generated by Django 6.0.6 on 2026-06-05 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=200)),
                (
                    "cover",
                    models.CharField(
                        choices=[("HARD", "Hard cover"), ("SOFT", "Soft cover")],
                        max_length=10,
                    ),
                ),
                ("inventory", models.PositiveIntegerField()),
                (
                    "daily_fee",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
